# Generated by Django 2.0 on 2019-10-02 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_auto_20191002_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('upto', models.CharField(blank=True, max_length=100, null=True, verbose_name='上级')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='金额')),
                ('type', models.CharField(default='', max_length=20, verbose_name='订单类型')),
                ('out_trade_no', models.CharField(default=0, max_length=100, verbose_name='订单号')),
                ('status', models.CharField(choices=[('0', '未付款'), ('1', '待接单'), ('2', '已退款'), ('3', '进行中'), ('4', '待评价'), ('5', '已完成'), ('6', '已付款')], default=0, max_length=1, verbose_name='状态')),
                ('detail', models.TextField(blank=True, default='', max_length=1000, verbose_name='订单备注')),
                ('ganxie', models.CharField(choices=[('0', '未感谢'), ('1', '已感谢')], default=0, max_length=1, verbose_name='是否感谢')),
                ('belong', models.CharField(choices=[('0', '非套餐'), ('1', '套餐')], default=0, max_length=1, verbose_name='是否感谢')),
                ('taocan', models.IntegerField(default=0, verbose_name='是否是套餐')),
                ('kaiqi', models.IntegerField(default=1, verbose_name='是否开启订单')),
                ('pid', models.IntegerField(default=0, verbose_name='所属问题')),
                ('comments', models.TextField(blank=True, default='', max_length=500, verbose_name='评价')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_userProfile', to=settings.AUTH_USER_MODEL, verbose_name='购买用户')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='teacher.Services', verbose_name='服务类别')),
                ('teacher', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teacher.Teachers', verbose_name='所属老师')),
                ('tomember', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL, verbose_name='所属老师昵称')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
            },
        ),
    ]
