# Generated by Django 2.0 on 2019-10-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191012_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='service',
        ),
    ]
