# Generated by Django 2.0 on 2019-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='upto',
        ),
        migrations.AddField(
            model_name='orders',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('0', '未付款'), ('1', '待接单'), ('2', '已退款'), ('3', '进行中'), ('4', '待评价'), ('5', '已完成'), ('6', '拒单')], default=0, max_length=1, verbose_name='状态'),
        ),
    ]
