# Generated by Django 2.0 on 2019-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191101_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='openid',
        ),
        migrations.AddField(
            model_name='orders',
            name='upto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='上级'),
        ),
    ]
