# Generated by Django 2.0 on 2019-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191101_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=50, verbose_name='用户名')),
                ('openid', models.TextField(blank=True, default='', max_length=50, verbose_name='订单备注')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='金额')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='申请时间')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='打款时间')),
            ],
            options={
                'verbose_name': '提现列表',
                'verbose_name_plural': '提现列表',
            },
        ),
    ]
