# Generated by Django 2.0 on 2019-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191112_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('0', '未打款'), ('1', '已结款')], default=0, max_length=1, verbose_name='状态'),
        ),
    ]
