# Generated by Django 2.0 on 2019-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_withdraw_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='updated',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='partner_trade_no',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='商户订单号'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='payment_no',
            field=models.TextField(blank=True, default='', max_length=64, verbose_name='微信付款单号'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='payment_time',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='付款成功时间'),
        ),
    ]
