# Generated by Django 2.0 on 2019-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191113_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='chatrecord',
            field=models.TextField(blank=True, default='', verbose_name='聊天记录'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='openid',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='用户识别码'),
        ),
    ]
