# Generated by Django 2.0 on 2019-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191119_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='belong',
            field=models.CharField(choices=[('0', '非套餐'), ('1', '套餐')], default=0, max_length=100, verbose_name='是否感谢'),
        ),
    ]
