# Generated by Django 2.0 on 2019-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191201_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='kaiqi',
            field=models.IntegerField(default=0, verbose_name='是否开启订单'),
        ),
    ]
