# Generated by Django 2.0 on 2019-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.CharField(blank=True, max_length=18, null=True, verbose_name='AppId')),
                ('AppSecret', models.CharField(blank=True, max_length=32, null=True, verbose_name='AppSecret')),
                ('ApiKey', models.CharField(blank=True, max_length=32, null=True, verbose_name='ApiKey')),
                ('MchID', models.CharField(blank=True, max_length=18, null=True, verbose_name='MchID')),
                ('DOMAIN', models.CharField(blank=True, max_length=132, null=True, verbose_name='DOMAIN')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '微信配置',
                'verbose_name_plural': '微信配置',
            },
        ),
    ]
