# Generated by Django 2.0 on 2019-10-09 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jifen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, verbose_name='识别码')),
                ('plus', models.CharField(choices=[('1', '增加'), ('2', '减少')], default='1', max_length=1, verbose_name='积分增减')),
                ('jifen', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='积分')),
                ('msg', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作原因')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='操作时间')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL, verbose_name='所属会员')),
            ],
            options={
                'verbose_name': '积分核销',
                'verbose_name_plural': '积分核销',
                'db_table': 'jifen',
            },
        ),
    ]
