# Generated by Django 2.0 on 2019-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jifen',
            name='member',
        ),
    ]
