# Generated by Django 2.0 on 2019-10-09 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0002_remove_jifen_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifen',
            name='openid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL, verbose_name='所属会员'),
        ),
    ]
