# Generated by Django 2.0 on 2019-10-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0003_auto_20191009_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifen',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='识别码'),
        ),
    ]
