# Generated by Django 2.0 on 2019-10-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jifen', '0004_auto_20191009_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifen',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL, verbose_name='所属会员'),
        ),
    ]
