# Generated by Django 2.0 on 2019-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0005_jifen_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifen',
            name='status',
            field=models.CharField(choices=[('0', '待审核'), ('1', '已通过'), ('2', '拒绝')], default='0', max_length=1, verbose_name='状态'),
        ),
    ]
