# Generated by Django 2.0 on 2019-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0006_jifen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifen',
            name='jifen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='jifen',
            name='plus',
            field=models.CharField(blank=True, choices=[('1', '增加'), ('2', '减少')], default='1', max_length=1, null=True, verbose_name='积分增减'),
        ),
        migrations.AlterField(
            model_name='jifen',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '待审核'), ('1', '已通过'), ('2', '拒绝')], default='0', max_length=1, null=True, verbose_name='状态'),
        ),
    ]
