# Generated by Django 2.0 on 2019-10-02 15:42

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=230, null=True, verbose_name='用户头像')),
                ('mobile', models.CharField(blank=True, help_text='电话号码', max_length=11, null=True, verbose_name='电话')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='', max_length=6, null=True, verbose_name='性别')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='日期类型')),
                ('year', models.CharField(blank=True, max_length=100, null=True, verbose_name='年月日')),
                ('realname', models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名')),
                ('seconds', models.CharField(blank=True, max_length=100, null=True, verbose_name='时辰')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('openid', models.CharField(blank=True, max_length=28, null=True, verbose_name='OPENID')),
                ('wechat', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号')),
                ('upto', models.CharField(blank=True, default='0', max_length=30, null=True, verbose_name='上级')),
                ('sharetime', models.CharField(blank=True, default='0', max_length=30, null=True, verbose_name='分享时间')),
                ('bindtime', models.CharField(blank=True, default='0', max_length=30, null=True, verbose_name='绑定时间')),
                ('update_status', models.CharField(blank=True, choices=[('1', '更改'), ('0', '未变')], default='0', max_length=6, null=True, verbose_name='更改状态')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
