# Generated by Django 2.0 on 2019-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191007_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=130, null=True, verbose_name='昵称'),
        ),
    ]
