# Generated by Django 2.0 on 2019-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191201_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shareurl',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='来源链接'),
        ),
    ]
