# Generated by Django 2.0 on 2019-10-02 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
                ('online', models.DateTimeField(default=datetime.datetime.now, verbose_name='上线时间')),
                ('offline', models.DateTimeField(default=datetime.datetime.now, verbose_name='下线时间')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='ads/', verbose_name='图片')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='广告类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '广告类别',
                'verbose_name_plural': '广告类别',
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='type',
            field=models.ManyToManyField(blank=True, to='ads.Type', verbose_name='广告类别'),
        ),
    ]
