# Generated by Django 2.0 on 2019-10-02 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='老师分类')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='category/', verbose_name='图标')),
            ],
            options={
                'verbose_name': '老师分类',
                'verbose_name_plural': '老师分类',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='套餐个数')),
                ('belong', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属服务')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='服务价格')),
                ('des', models.TextField(blank=True, default='', null=True, verbose_name='服务描述')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=10, verbose_name='真实姓名')),
                ('resume', models.TextField(max_length=250, null=True, verbose_name='个人介绍')),
                ('haopinglv', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='好评率')),
                ('display', models.CharField(choices=[('1', '上线'), ('0', '下线')], default=0, max_length=1, verbose_name='展示状态')),
                ('online', models.CharField(choices=[('1', '上线'), ('0', '下线')], default=0, max_length=1, verbose_name='上线状态')),
                ('rec', models.CharField(choices=[('1', '上线'), ('0', '下线')], default=0, max_length=1, verbose_name='置顶状态')),
                ('honor', models.CharField(max_length=150, null=True, verbose_name='头衔')),
                ('experience', models.CharField(max_length=1000, null=True, verbose_name='经验')),
                ('wechat', models.CharField(max_length=90, null=True, verbose_name='微信号')),
                ('telphone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('area', models.CharField(blank=True, default='', max_length=180, verbose_name='所在地区')),
                ('star', models.CharField(blank=True, default='', max_length=10, verbose_name='星座')),
                ('bloodtype', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('0', '不知道')], default='', max_length=6, null=True, verbose_name='血型')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='', max_length=6, null=True, verbose_name='性别')),
                ('status', models.CharField(blank=True, choices=[('1', '通过'), ('2', '等待审核'), ('3', '拒绝')], default='0', max_length=6, null=True, verbose_name='审核状态')),
                ('msg', models.CharField(blank=True, max_length=300, null=True, verbose_name='审核理由')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '老师列表',
                'verbose_name_plural': '老师列表',
            },
        ),
    ]
