# Generated by Django 2.0 on 2019-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20191205_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='分成比例'),
        ),
    ]
