# Generated by Django 2.0 on 2019-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_services_proportion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default='40.00', max_digits=15, verbose_name='分成比例'),
        ),
    ]
