# Generated by Django 2.0 on 2019-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='名称')),
                ('note', models.CharField(blank=True, max_length=30, null=True, verbose_name='标志符')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '逛逛分类',
                'verbose_name_plural': '逛逛分类',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='价格')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('1', '显示'), ('0', '不显示')], default=0, max_length=1, verbose_name='状态')),
                ('cover', models.CharField(blank=True, max_length=140, null=True, verbose_name='封面图')),
                ('big', models.CharField(blank=True, max_length=140, null=True, verbose_name='大图')),
                ('des', models.TextField(blank=True, max_length=300, null=True, verbose_name='简介')),
                ('detail', models.TextField(blank=True, max_length=300, null=True, verbose_name='详情')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '应用列表',
                'verbose_name_plural': '应用列表',
            },
        ),
    ]
