# Generated by Django 2.0 on 2019-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191002_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default='40.00', max_digits=15, verbose_name='分成比例'),
        ),
    ]
